dataset_path: "data/raw/water_potability.csv"  
target: "Potability"

numerical_features:
  - ph
  - Hardness
  - Solids
  - Chloramines
  - Sulfate
  - Conductivity
  - Organic_carbon
  - Trihalomethanes
  - Turbidity

categorical_features: []
