strategy: "loo"  # "holdout" | "kfold" | "loo" | "kfold" | "repeated_holdout" | "repeated_kfold"
# splits are the number of repetitions, use stratified for unbalaned classes
repeated_kfold:
  n_splits: 5
  n_repeats: 10
  random_state: 42
  stratified: true
holdout:
  test_size: 0.2
  random_state: 42
  stratify: true
kfold:
  n_splits: 5
  stratified: true
  shuffle: true
  random_state: 42
loo: {}
repeated_holdout:
  test_size: 0.2
  n_splits: 50      
  random_state: 42
  stratify: true